base_url = "https://chaoticenginerd.com"

title = "chaoticenginerd.com"
description = "Tosh's home on the internet."

compile_sass = false
build_search_index = false

generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "inspired-github"

[extra]
author = "Tosh"
favicon = "favicon.png"
stylesheet = "css/styles.css"
